config/routes.rb
Rails.application.routes.draw do
  root "lists#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :lists, only: [ :index, :show, :new, :create, :destroy ] do
    resources :bookmarks, only: [ :new, :create ]
  end

   resources :bookmarks, only: [ :destroy ]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :list, through: :bookmarks

  validates :title, :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new()
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy

  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show destroy]
  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new()
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1 class="index">Add a movie to the list</h1>
<div class="container">
<%= simple_form_for [@list, @bookmark] do |m| %>
  <%= m.association :movie %>
  <%= m.input :comment, as: :text %>
  <%= m.submit "Add movie", class:"btn btn-danger" %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Watch List" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Rails Watch List">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-light">
    <nav class="navbar-lewagon bg-body-tertiary">
      <div class="d-flex justify-content-between">
          <%= link_to lists_path do %>
            <button class="btn btn-danger">My lists</button>
          <% end %>
          <%= link_to new_list_path do %>
            <button class="btn btn-danger">Add a list</button>
          <% end %>
      </div>
    </nav>


    <%= yield %>
  </body>
</html>

app/views/lists/_list_form.html.erb
<div class="d-flex m-5">
<%= simple_form_for (list) do |f| %>
<%= f.input :name %>
<%= f.input :photo, as: :file %>
<%= f.submit class:"btn btn-danger m-2" %>
<% end %>
</div>

app/views/lists/index.html.erb
<div class="index">
  <h1>My movie lists</h1>
</div>
<div class="row">
  <% @lists.each do |l| %>
    <div class="col-3 m-5">
      <%= link_to list_path(l), class: "text-decoration-none" do %>
        <div class="cards" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path l.photo.key, height: 300, crop: :fill %>')">
          <p><%= l.name %></p>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="index">
<h1>Add your list</h1>
</div>
<div class="container">
<%= render "lists/list_form", list:  @list %>
</div>

app/views/lists/show.html.erb
<div class="show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>')">
  <h1><%= @list.name %></h1>
</div>

<div class="show-btn">
  <%= link_to  new_list_bookmark_path(@list) do %>
    <button class="btn btn-danger">Add a movie</button>
  <% end %>

  <%= link_to  list_path(@list), data: {turbo_method: :delete} do %>
    <button class="btn btn-danger me-4">Delete List</button>
  <% end %>
</div>
<div class="row">
    <% @list.movies.each do |b| %>
  <div class="col-4 m-3">
    <div class="cards-show">
      <div class="d-flex flex-column m-2">
        <h3 class="m-3"><%= b.title %></h3>
        <p>Overview : <%= b.overview.split.take(10).join(" ") %>...</p>
      </div>
      <%= image_tag b.poster_url, class:"poster" %>
    </div>
  </div>
    <% end %>
</div>